[build]
arch = "amd64"
packages = ["btop"] # for testing
sources-list = [
    "deb https://idnos.github.io/repo/idnos tangguh core",
    "deb https://deb.debian.org/debian bullseye main contrib non-free",
    "deb https://deb.debian.org/debian bullseye-updates main contrib non-free",
    "deb https://security.debian.org bullseye-security main contrib non-free"
]

outdir = "build/"

# vim: set ts=4 sw=4 expandtab ai:
